server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/live
    username: root
    password: 123456
    # &#x4F7F;&#x7528;druid&#x6570;&#x636E;&#x6E90;
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

## &#x8BE5;&#x914D;&#x7F6E;&#x8282;&#x70B9;&#x4E3A;&#x72EC;&#x7ACB;&#x7684;&#x8282;&#x70B9;&#xFF0C;&#x6709;&#x5F88;&#x591A;&#x540C;&#x5B66;&#x5BB9;&#x6613;&#x5C06;&#x8FD9;&#x4E2A;&#x914D;&#x7F6E;&#x653E;&#x5728;spring&#x7684;&#x8282;&#x70B9;&#x4E0B;&#xFF0C;&#x5BFC;&#x81F4;&#x914D;&#x7F6E;&#x65E0;&#x6CD5;&#x88AB;&#x8BC6;&#x522B;
mybatis:
  ##mybatis.mapper-locations=classpath*:/mapper/**Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml  #&#x6CE8;&#x610F;&#xFF1A;&#x4E00;&#x5B9A;&#x8981;&#x5BF9;&#x5E94;mapper&#x6620;&#x5C04;xml&#x6587;&#x4EF6;&#x7684;&#x6240;&#x5728;&#x8DEF;&#x5F84;
  type-aliases-package: com.dlyong.live.model  # &#x6CE8;&#x610F;&#xFF1A;&#x5BF9;&#x5E94;&#x5B9E;&#x4F53;&#x7C7B;&#x7684;&#x8DEF;&#x5F84;

#pagehelper&#x5206;&#x9875;&#x63D2;&#x4EF6;
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com.dlyong.live.mapper: DEBUG